Repository ReliefApplications/oort-frontend, pull requests merged in 2023-11, with the labels that each got.

#2 Fix/hit 166 error trying to duplicate resources
  apps/back-office/src/app/dashboard/pages/resources/graphql/mutations.ts
  apps/back-office/src/app/dashboard/pages/resources/resources.component.ts
  libs/shared/src/lib/models/resource.model.ts
Labels: bug, enhancement

#5 Fix/hit 168 front office menu text not updating language
  apps/back-office/src/app/application/application.component.ts
  apps/front-office/src/app/application/application.component.ts
Labels: bug

#6 fixed a bug where tooltip would never appear on widgets in front-office
  libs/shared/src/lib/components/widget-grid/widget-actions/widget-actions.component.html
Labels: bug

#7 Fix/hit 173 search text appearing in english on resources question
  libs/shared/src/lib/components/form-builder/form-builder.component.ts
  libs/shared/src/lib/components/form/form.component.ts
  libs/shared/src/lib/survey/components/resource.ts
  libs/shared/src/lib/survey/components/resources.ts
  libs/shared/src/lib/survey/components/utils.ts
Labels: bug

#8 Added options to show/hide close button and ask for confirmation when…
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/i18n/test.json
  libs/shared/src/lib/components/form-modal/form-modal.component.html
  libs/shared/src/lib/components/form-modal/form-modal.component.ts
  libs/shared/src/lib/survey/global-properties/others.ts
Labels: enhancement

#13 fix/HIT-169_Go-to-next-page-automatically-not-working
  apps/front-office/src/app/application/pages/form/graphql/queries.ts
Labels: bug

#14 fix/HIT-182-search-by-id-not-working-on-the-grid
  libs/shared/src/lib/utils/filter/search-filters.ts
Labels: bug, enhancement

#16 feat/HIT-164_Add-ability-to-filter-by-current-user-on-aggregations
  libs/shared/src/lib/components/filter/filter-row/filter-row.component.ts
  libs/shared/src/lib/components/ui/aggregation-builder/aggregation-builder.component.ts
  libs/shared/src/lib/components/ui/aggregation-builder/graphql/queries.ts
Labels: enhancement

#4 Fix/HIT-137-re-add-features-lost-during-merge
  libs/shared/src/lib/components/form-actions/form-actions.component.ts
  libs/shared/src/lib/components/form-builder/form-builder.component.ts
  libs/shared/src/lib/services/form-builder/form-builder.service.ts
  libs/shared/src/lib/survey/controllers/matrixManager.ts
  libs/shared/src/lib/survey/global-properties/others.ts
Labels: bug, enhancement, refactor
